# Generated by Django 6.0.3 on 2026-03-25 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_visible', models.BooleanField(default=True, verbose_name='Mostrar banner')),
                ('banner_badge_text', models.CharField(default='Sistema de Autenticacao', max_length=80, verbose_name='Texto da badge do banner')),
                ('banner_title', models.CharField(default='Bem-vindo ao Codex', max_length=180, verbose_name='Titulo do banner')),
                ('banner_subtitle', models.TextField(default='Home com area personalizada para Admin e Usuario comum.', verbose_name='Subtitulo do banner')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='home/banner/', verbose_name='Imagem do banner (horizontal)')),
                ('menu_section_visible', models.BooleanField(default=True, verbose_name='Mostrar secao de menu')),
                ('menu_section_title', models.CharField(default='Menu', max_length=120, verbose_name='Titulo da secao de menu')),
                ('text_section_visible', models.BooleanField(default=True, verbose_name='Mostrar secao de texto')),
                ('text_section_title', models.CharField(default='Sobre a plataforma', max_length=140, verbose_name='Titulo da secao de texto')),
                ('text_section_content', models.TextField(default='Edite este conteudo no admin para destacar informacoes importantes na Home.', verbose_name='Conteudo da secao de texto')),
            ],
            options={
                'verbose_name': 'Configuracao da Home',
                'verbose_name_plural': 'Configuracao da Home',
            },
        ),
        migrations.CreateModel(
            name='SiteLayoutConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_visible', models.BooleanField(default=True, verbose_name='Mostrar cabecalho')),
                ('header_title', models.CharField(default='Codex', max_length=120, verbose_name='Titulo do cabecalho')),
                ('footer_visible', models.BooleanField(default=True, verbose_name='Mostrar rodape')),
                ('footer_title', models.CharField(default='Codex da Cachoeira', max_length=120, verbose_name='Titulo do rodape')),
                ('footer_description', models.CharField(default='Plataforma com login, registro e perfis de acesso.', max_length=220, verbose_name='Descricao do rodape')),
                ('footer_copyright', models.CharField(default='© 2026 - Todos os direitos reservados.', max_length=160, verbose_name='Linha de copyright')),
            ],
            options={
                'verbose_name': 'Layout padrao do site',
                'verbose_name_plural': 'Layout padrao do site',
            },
        ),
    ]
