# Generated by Django 6.0.3 on 2026-03-25 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_homepageconfig_sitelayoutconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeDynamicSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140, verbose_name='Titulo')),
                ('content', models.TextField(verbose_name='Conteudo')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Mostrar secao')),
                ('display_order', models.PositiveIntegerField(default=1, verbose_name='Ordem de exibicao')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Componente extra da Home',
                'verbose_name_plural': 'Componentes extras da Home',
                'ordering': ('display_order', 'id'),
            },
        ),
    ]
