# Generated by Django 6.0.3 on 2026-03-27 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_profile_larp_fields'),
        ('personagens', '0004_alter_personagem_classe_alter_personagem_guilda'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LarpEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=180)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('historia', models.TextField()),
                ('local', models.CharField(max_length=180)),
                ('data_evento', models.DateTimeField()),
                ('visivel_publicamente', models.BooleanField(default=False)),
                ('inscricao_token', models.CharField(editable=False, max_length=32, unique=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_larp_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento LARP',
                'verbose_name_plural': 'Eventos LARP',
                'ordering': ('-data_evento', '-id'),
            },
        ),
        migrations.CreateModel(
            name='LarpInscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo_jogador', models.CharField(max_length=180)),
                ('apelido_cla', models.CharField(blank=True, max_length=120)),
                ('telefone', models.CharField(max_length=30)),
                ('cpf', models.CharField(max_length=14)),
                ('fobia_gatilho', models.TextField(blank=True)),
                ('confirmacao_final', models.BooleanField(default=False)),
                ('data_inscricao', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='core.larpevento')),
                ('personagem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscricoes_larp', to='personagens.personagem')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes_larp', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inscricao LARP',
                'verbose_name_plural': 'Inscricoes LARP',
                'ordering': ('-data_inscricao', '-id'),
                'constraints': [models.UniqueConstraint(fields=('evento', 'usuario'), name='unique_inscricao_por_evento_usuario')],
            },
        ),
    ]
