# Generated by Django 6.0.3 on 2026-03-27 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_larpevento_larpinscricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='larpinscricao',
            name='taxa_paga',
            field=models.BooleanField(default=False),
        ),
    ]
