# Generated by Django 5.2.6 on 2026-03-30 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_larpinscricao_taxa_paga'),
    ]

    operations = [
        migrations.CreateModel(
            name='RotativeBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='home/banners_rotativos/', verbose_name='Imagem do banner (2000x542)')),
                ('url_redirecionamento', models.URLField(max_length=500, verbose_name='URL para redirecionamento')),
                ('texto_alternativo', models.CharField(blank=True, max_length=200, verbose_name='Texto alternativo (alt) da imagem')),
                ('ordem_exibicao', models.PositiveIntegerField(default=1, verbose_name='Ordem de exibicao')),
                ('ativo', models.BooleanField(default=True, verbose_name='Mostrar este banner')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Banner Rotativo',
                'verbose_name_plural': 'Banners Rotativos',
                'ordering': ('ordem_exibicao', 'id'),
            },
        ),
        migrations.AddField(
            model_name='homepageconfig',
            name='banner_type',
            field=models.CharField(choices=[('EDITORIAL', 'Banner Editorial (com texto)'), ('ROTATIVO', 'Banner Rotativo (solo imagem)')], default='EDITORIAL', max_length=10, verbose_name='Tipo de banner'),
        ),
        migrations.AlterField(
            model_name='homedynamicsection',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='homepageconfig',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='larpevento',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='larpinscricao',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sitelayoutconfig',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
