# Generated by Django 5.2.6 on 2026-03-30 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rotativebanner_homepageconfig_banner_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='larpinscricao',
            name='dinheiro_ganho',
            field=models.IntegerField(default=0, verbose_name='Dinheiro ganho no LARP'),
        ),
        migrations.AddField(
            model_name='larpinscricao',
            name='dinheiro_gasto',
            field=models.IntegerField(default=0, verbose_name='Dinheiro gasto no LARP'),
        ),
        migrations.AddField(
            model_name='larpinscricao',
            name='entrada_larp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Entrada no LARP'),
        ),
        migrations.AddField(
            model_name='larpinscricao',
            name='morreu_no_larp',
            field=models.BooleanField(default=False, verbose_name='Morreu no LARP'),
        ),
        migrations.AddField(
            model_name='larpinscricao',
            name='saida_larp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Saida do LARP'),
        ),
        migrations.AddField(
            model_name='larpinscricao',
            name='xp_ganho',
            field=models.IntegerField(default=0, verbose_name='XP ganho no LARP'),
        ),
    ]
