# Generated by Django 5.2.6 on 2026-03-30 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_larpinscricao_dinheiro_ganho_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='larpinscricao',
            name='dinheiro_final_larp',
            field=models.IntegerField(blank=True, null=True, verbose_name='Dinheiro no final do LARP'),
        ),
        migrations.AddField(
            model_name='larpinscricao',
            name='dinheiro_inicio_larp',
            field=models.IntegerField(blank=True, null=True, verbose_name='Dinheiro no inicio do LARP'),
        ),
        migrations.AddField(
            model_name='larpinscricao',
            name='faltou_no_larp',
            field=models.BooleanField(default=False, verbose_name='Faltou no LARP'),
        ),
    ]
