# Generated by Django 5.2.6 on 2026-03-30 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_larpinscricao_dinheiro_final_larp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='larpinscricao',
            name='dinheiro_pego_larp',
            field=models.IntegerField(default=0, verbose_name='Dinheiro pego para o LARP'),
        ),
    ]
