# Generated by Django 5.2.6 on 2026-03-30 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_larpevento_inscricao_ate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitelayoutconfig',
            name='footer_description',
            field=models.CharField(default='Plataforma com autenticacao segura, cadastro de usuarios e perfis de acesso.', max_length=220, verbose_name='Descricao do rodape'),
        ),
    ]
