# Generated by Django 6.0.3 on 2026-09-30 13:47

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_larp_registration_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, validators=[core.validators.validate_birth_date], verbose_name='Data de nascimento'),
        ),
    ]
