# Generated by Django 6.0.3 on 2026-09-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_profile_data_nascimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='homedynamicsection',
            name='eyebrow',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='homedynamicsection',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='homedynamicsection',
            name='kind',
            field=models.CharField(choices=[('text', 'Texto'), ('community', 'Comunidade / guildas'), ('banner', 'Banner'), ('links', 'Atalhos')], default='text', max_length=20),
        ),
    ]
