# Generated by Django 6.0.3 on 2026-09-30 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_seed_home_community'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(blank=True, upload_to='images/')),
                ('url', models.URLField(blank=True)),
                ('x', models.PositiveSmallIntegerField(default=50)),
                ('y', models.PositiveSmallIntegerField(default=50)),
                ('zoom', models.FloatField(default=1)),
                ('ratio', models.FloatField(default=1)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='homedynamicsection',
            name='image_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.imageasset'),
        ),
        migrations.AddField(
            model_name='profile',
            name='image_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.imageasset'),
        ),
    ]
