# Generated by Django 6.0.3 on 2026-09-30 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_imageasset_homedynamicsection_image_asset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homedynamicsection',
            name='button_label',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='homedynamicsection',
            name='button_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='homedynamicsection',
            name='secondary_label',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='homedynamicsection',
            name='secondary_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='homedynamicsection',
            name='kind',
            field=models.CharField(choices=[('text', 'Texto'), ('community', 'Comunidade / guildas'), ('banner', 'Banner dividido'), ('callout', 'Chamada centralizada'), ('links', 'Atalhos')], default='text', max_length=20),
        ),
    ]
