# Generated by Django 6.0.3 on 2026-09-30 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_homedynamicsection_button_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageasset',
            name='x',
            field=models.FloatField(default=50),
        ),
        migrations.AlterField(
            model_name='imageasset',
            name='y',
            field=models.FloatField(default=50),
        ),
    ]
