# Generated by Django 6.0.3 on 2026-09-30 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_imageasset_x_alter_imageasset_y'),
    ]

    operations = [
        migrations.AddField(
            model_name='larpevento',
            name='capa',
            field=models.ImageField(blank=True, null=True, upload_to='larps/capas/', verbose_name='Capa do evento'),
        ),
    ]
