# Generated by Django 6.0.3 on 2026-10-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_larpevento_capa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homedynamicsection',
            name='kind',
            field=models.CharField(choices=[('text', 'Texto'), ('community', 'Comunidade / guildas'), ('banner', 'Banner dividido'), ('callout', 'Chamada centralizada'), ('links', 'Atalhos'), ('event', 'Evento')], default='text', max_length=20),
        ),
    ]
