CLASSES_WIKI = {
    "BARBARO": {
        "nome": "Bárbaro",
        "imagem": "core/img/classes/Barbaro.png",
        "tipo": "Combatente corpo a corpo",
        "descricao": "Guerreiro tribal, normalmente selvagem, que ganha poder de sua fúria e instinto de luta.",
        "sabe_usar": "Armas corpo-a-corpo curtas, médias ou longas.",
        "defesas": "Pode usar até 3 peças de armadura ou 1 peça de armadura + escudo.",
        "magia": "Não sabe conjurar naturalmente.",
        "item_inicial": "Duas sementes dos deuses ou uma semente e um antídoto.",
        "habilidade_especial": "Fúria ou Intimidação (habilidade de uso único).",
        "habilidade_detalhes": [
            "Fúria: grita 'FÚRIA', ganha 3 PVs adicionais, imunidade a desmembramento e intimidação, e pode atacar com BRUTAL usando arma média ou longa com ambas as mãos.",
            "Intimidação: fora de combate, grita 'INTIMIDAÇÃO' e dá um comando simples ou faz uma pergunta; o alvo obedece dentro dos limites da habilidade.",
        ],
    },

    "BARDO": {
        "nome": "Bardo",
        "imagem": "core/img/classes/Bardo.png",
        "tipo": "Conjurador de suporte e manipulação",
        "descricao": "Artista de ruas ou cortes, capaz de fazer magia pelo poder da sua música.",
        "sabe_usar": "Armas corpo-a-corpo curtas e de arremesso.",
        "defesas": "Pode usar até 2 peças de armadura. Não sabe usar escudo.",
        "magia": "Escolha 3: Antídoto Mágico, Contramágica, Lentidão, Silenciar, Versos de Proteção, Vigor do Touro.",
        "item_inicial": "2 DO adicionais.",
        "habilidade_especial": "Truques de Bardo (habilidade de uso único, efeito mental).",
        "habilidade_detalhes": [
            "Carisma: convence um alvo de que uma afirmação é verdadeira até que algo prove o contrário.",
            "Libertar: grita 'LIBERTAR ALIADOS' para libertar seu grupo de um efeito mental ou possessão.",
        ],
        "extra": "Dom de Bardo: pode cantar no lugar de tocar um instrumento como foco.",
    },

    "CACADOR": {
        "nome": "Caçador",
        "imagem": "core/img/classes/Caçador.png",
        "tipo": "Combatente tático e rastreador",
        "descricao": "Mestres da selva ou caçadores de recompensa, experts em encontrar e eliminar suas presas.",
        "sabe_usar": "Armas corpo-a-corpo médias e curtas e armas à distância.",
        "defesas": "Pode usar até 3 peças de armadura. Não sabe usar escudo.",
        "magia": "Não sabe conjurar naturalmente.",
        "item_inicial": "Duas sementes dos deuses ou dois antídotos ou uma semente e um antídoto.",
        "habilidade_especial": "Técnicas de Caça (habilidade de uso único).",
        "habilidade_detalhes": [
            "Armadilha: ao atingir um alvo com ataque, diga 'ARMADILHA' e ele não pode sair do lugar por 15 segundos.",
            "Marcar a presa: escolhe um inimigo e pode usar 5 ataques com BRUTAL ou VENENO contra ele até o final do LARP.",
            "Percepção: revela alguém furtivo próximo ao gritar 'PERCEPÇÃO'.",
        ],
    },

    "CLERIGO": {
        "nome": "Clérigo",
        "imagem": "core/img/classes/Clérigo.png",
        "tipo": "Conjurador divino e curandeiro",
        "descricao": "Sacerdote mágico que consegue poder através da fé em sua divindade.",
        "sabe_usar": "Armas corpo-a-corpo curtas ou médias (não usa dual); cajado.",
        "defesas": "2 peças de armadura OU um escudo.",
        "magia": "Escolha 3: Barreira Mágica, Antídoto Mágico, Exorcismo, Lentidão, Toque da Cura ou Versos da Proteção.",
        "item_inicial": "1 água benta ou 1 antídoto e 1 semente dos deuses.",
        "habilidade_especial": "Milagres.",
        "habilidade_detalhes": [
            "Recupera todos os PVs e cura todos os desmembramentos de um alvo.",
            "Se o alvo estiver morto, ele é ressuscitado seguindo as regras de ressurreição.",
            "Pode ser usado quantas vezes quiser por sessão, mas não durante combates.",
            "Não cura veneno.",
        ],
    },

    "DRUIDA": {
        "nome": "Druida",
        "imagem": "core/img/classes/Druida.png",
        "tipo": "Conjurador natural e transformista",
        "descricao": "Sacerdote das matas, ligado ao poder da natureza e de seus espíritos.",
        "sabe_usar": "Armas corpo-a-corpo curtas, médias ou longas; manopla de garras; cajado.",
        "defesas": "Nenhuma.",
        "magia": "Antídoto Mágico, Comunhão com a Natureza e Toque da Cura (as três).",
        "item_inicial": "Duas sementes dos deuses ou dois antídotos ou uma semente e um antídoto.",
        "habilidade_especial": "Forma Selvagem (habilidade de uso único).",
        "habilidade_detalhes": [
            "Transforma-se em um aspecto da natureza por 5 minutos, até o fim do combate ou até cancelar a forma.",
            "A forma possui três características definidas pela comissão e um defeito.",
        ],
        "extra": "Dom de Druida: pode usar mato, flores ou folhas como foco.",
    },

    "GUERREIRO": {
        "nome": "Guerreiro",
        "imagem": "core/img/classes/Guerreiro.png",
        "tipo": "Combatente marcial resistente",
        "descricao": "Soldado treinado para vencer missões perigosas apenas com suas armas e estratégia.",
        "sabe_usar": "Armas corpo-a-corpo curtas, médias e longas.",
        "defesas": "4 peças de armadura OU 2 peças de armadura + escudo.",
        "magia": "Não sabe conjurar naturalmente.",
        "item_inicial": "Duas sementes dos deuses ou duas doses de veneno ou um veneno e uma semente.",
        "habilidade_especial": "Determinação (habilidade de uso único).",
        "habilidade_detalhes": [
            "Depois de cair incapacitado, pode gritar 'DETERMINAÇÃO' e voltar com 1 PV.",
            "Não fica sofrendo desmembramento, mas não pode correr até ser completamente curado.",
            "Também cancela envenenamento.",
        ],
    },

    "LADINO": {
        "nome": "Ladino",
        "imagem": "core/img/classes/Ladino.png",
        "tipo": "Furtividade, roubo e mobilidade",
        "descricao": "Ladrões e espiões de ações sorrateiras e movimentos ágeis, prontos a agir nas sombras.",
        "sabe_usar": "Armas corpo-a-corpo curtas; armas de arremesso; armas à distância.",
        "defesas": "Até 3 peças de armadura; não sabe usar escudo.",
        "magia": "Não sabe conjurar naturalmente.",
        "item_inicial": "2 DO adicionais.",
        "habilidade_especial": "Furtividade (habilidade de uso único).",
        "habilidade_detalhes": [
            "Ao gritar 'FURTIVIDADE' e colocar os braços atrás da cabeça, o personagem fica escondido.",
            "Também pode ser usada para roubar fora de combate.",
            "Também pode ser usada para fugir de amarras.",
        ],
    },

    "MAGO": {
        "nome": "Mago",
        "imagem": "core/img/classes/Mago.png",
        "tipo": "Conjurador arcano ofensivo e utilitário",
        "descricao": "Alguém que se conectou com o poder da Cachoeira e aprendeu a manipular a magia.",
        "sabe_usar": "Adaga (mas não sabe usar dual); esferas de magia; cajado ou varinha.",
        "defesas": "Nenhuma.",
        "magia": "Escolha 4: Barreira Mágica, Bola de Fogo, Contramágica, Exorcismo, Lentidão, Raio Elétrico, Silenciar e Vigor do Touro.",
        "item_inicial": "2 balões de bola de fogo ou um amuleto de proteção espiritual.",
        "habilidade_especial": "Feitiços de Magia Antiga (habilidade de uso único).",
        "habilidade_detalhes": [
            "Controle Mental: dá uma ordem ao alvo por 30 segundos.",
            "Necromancia: transforma um incapacitado ou morto em zumbi, ou invoca o espectro para responder perguntas.",
            "Petrificação: petrifica um alvo enquanto mantiver a magia.",
        ],
    },

    "PALADINO": {
        "nome": "Paladino",
        "imagem": "core/img/classes/Paladino.png",
        "tipo": "Combatente sagrado",
        "descricao": "Guerreiro sagrado que leva a palavra de sua divindade, exemplo de honra e justiça.",
        "sabe_usar": "Armas corpo-a-corpo curtas, médias e longas.",
        "defesas": "Até 2 peças de armadura + um escudo.",
        "magia": "Toque da Cura e Exorcismo (as duas).",
        "item_inicial": "Duas sementes dos deuses ou uma água benta.",
        "habilidade_especial": "Proteção Divina (habilidade de uso único).",
        "habilidade_detalhes": [
            "Grita 'PROTEÇÃO' e fica imune a desmembramento até o fim do combate.",
            "Também fica imune a efeitos mentais, espirituais e intimidação até o fim do combate ou por 5 minutos.",
            "Contra zumbis, possuídos e seres das trevas, seus ataques podem usar BRUTAL.",
        ],
        "extra": "Dom de Paladino: se o símbolo da divindade estiver na frente do escudo, o escudo conta como foco de magia.",
    },
}