# Generated by Django 5.2.6 on 2026-03-25 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guilda',
            fields=[
                ('guilda_id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('descricao_interna', models.TextField(blank=True, help_text='Informações internas visíveis apenas para membros')),
                ('total_membros', models.PositiveIntegerField(default=0)),
                ('total_personagens', models.PositiveIntegerField(default=0)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('ativa', models.BooleanField(default=True, help_text='Guilda visível e ativa')),
            ],
            options={
                'verbose_name': 'Guilda',
                'verbose_name_plural': 'Guildas',
                'ordering': ['guilda_id'],
            },
        ),
        migrations.CreateModel(
            name='GuildaNoticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('conteudo', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('publicado', models.BooleanField(default=True)),
                ('guilda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noticias', to='guildas.guilda')),
            ],
            options={
                'verbose_name': 'Notícia da Guilda',
                'verbose_name_plural': 'Notícias das Guildas',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='GuildaMembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateTimeField(auto_now_add=True)),
                ('guilda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros', to='guildas.guilda')),
                ('usuario', models.ForeignKey(help_text='Usuário que possui pelo menos 1 personagem na guilda', on_delete=django.db.models.deletion.CASCADE, related_name='guildas_membro', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membro da Guilda',
                'verbose_name_plural': 'Membros das Guildas',
                'unique_together': {('guilda', 'usuario')},
            },
        ),
    ]
