# Generated by Django 6.0.3 on 2026-03-25 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Personagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('historia', models.TextField(blank=True)),
                ('aparencia', models.TextField(blank=True)),
                ('objetivos', models.TextField(blank=True)),
                ('personalidade', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('ATIVO', 'Ativo'), ('INATIVO', 'Inativo'), ('MORTO', 'Morto')], default='RASCUNHO', max_length=20)),
                ('guilda', models.CharField(blank=True, max_length=120)),
                ('classe', models.CharField(blank=True, max_length=120)),
                ('xp_atual', models.PositiveIntegerField(default=0)),
                ('ouro', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('aprovado', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personagens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Personagem',
                'verbose_name_plural': 'Personagens',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
