# Generated by Django 6.0.3 on 2026-03-27 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personagens', '0003_personagem_magias_talentos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personagem',
            name='classe',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Bárbaro'), (2, 'Bardo'), (3, 'Caçador'), (4, 'Clérigo'), (5, 'Druida'), (6, 'Guerreiro'), (7, 'Ladino'), (8, 'Mago'), (9, 'Paladino')], null=True),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='guilda',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Artistas da Revolução'), (2, 'Círculo do Fogo'), (3, 'Floresta do Sol'), (4, 'Irmandade das Tavernas'), (5, 'Os Rasga-Mortalhas'), (6, 'Sociedade Zaori'), (7, 'Mercenários Independentes')], null=True),
        ),
    ]
