# Generated by Django 6.0.3 on 2026-10-01 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_larpevento_capa'),
        ('personagens', '0004_alter_personagem_classe_alter_personagem_guilda'),
    ]

    operations = [
        migrations.AddField(
            model_name='personagem',
            name='image_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.imageasset'),
        ),
    ]
